#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from tema.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "tema.y"

#include <stdio.h>
#include "semantica.h"

extern FILE* yyin;
extern char* yytext;
extern void yyerror();
extern int yylex();

void popScope();
void pushScope(char*);
void scriereInTabelDeSimboluri();
void declarareClasa(char*);
void apelFunctie(char *);
void declarareVariabila(char* ,char*,char*, int);
void endAssign(char *);
void pushExpresieValuePeStack(char *);
void pushExpresieIdPeStack(char *);
void startAssignExpr(char *);
void declarareFunctie(char*, char*);
void asignareVariabila();
void expresieValoareAsignare(char*);
void evalNumberExpr(char* ,char*,char*, char*);
void evalExpresieBool(char* ,char*,char*, char*);
void evalIdNumberExpr(char*, char*);
void pushOperatorStack(char*);
void pushStackParan();
void popStackParan(char*);
void apelFunctie(char*);
void endApelFunctie(char*);
void evaluareIdCaBool(char*, char*);

#line 34 "tema.y"
typedef union {
  char * tip;
  char * uTipBool;
  char * uTipString;
  char * id;

  char * numericValoare;
  char * exprNumeric;

  char * boolValoare;
  char * exprBool;
  char * operator;
  
  char * stringValue;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	STRCMP	258
#define	STRCPY	259
#define	STRCAT	260
#define	RETURN	261
#define	CONSTRUCT	262
#define	CLASS	263
#define	IF	264
#define	WHILE	265
#define	FOR	266
#define	ELSE	267
#define	START	268
#define	END	269
#define	START_FUN	270
#define	END_FUN	271
#define	BGIN_CLASS	272
#define	END_CLASS	273
#define	SECURE1	274
#define	SECURE2	275
#define	START_SECURE1	276
#define	END_SECURE1	277
#define	START_SECURE2	278
#define	END_SECURE2	279
#define	FLOAT	280
#define	INT	281
#define	VOID	282
#define	ID	283
#define	ID_FUNCTIE	284
#define	BOOL_VALOARE	285
#define	INTEGER_VALOARE	286
#define	FLOAT_VALOARE	287
#define	BOOL	288
#define	STRING	289
#define	STRING_VALOARE	290
#define	ASSIGN	291
#define	NEG	292
#define	EGAL	293
#define	MAI_MIC	294
#define	MIC_EGAL	295
#define	MAI_MARE	296
#define	MARE_EGAL	297
#define	AND	298
#define	OR	299


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int STRCMP;
static const int STRCPY;
static const int STRCAT;
static const int RETURN;
static const int CONSTRUCT;
static const int CLASS;
static const int IF;
static const int WHILE;
static const int FOR;
static const int ELSE;
static const int START;
static const int END;
static const int START_FUN;
static const int END_FUN;
static const int BGIN_CLASS;
static const int END_CLASS;
static const int SECURE1;
static const int SECURE2;
static const int START_SECURE1;
static const int END_SECURE1;
static const int START_SECURE2;
static const int END_SECURE2;
static const int FLOAT;
static const int INT;
static const int VOID;
static const int ID;
static const int ID_FUNCTIE;
static const int BOOL_VALOARE;
static const int INTEGER_VALOARE;
static const int FLOAT_VALOARE;
static const int BOOL;
static const int STRING;
static const int STRING_VALOARE;
static const int ASSIGN;
static const int NEG;
static const int EGAL;
static const int MAI_MIC;
static const int MIC_EGAL;
static const int MAI_MARE;
static const int MARE_EGAL;
static const int AND;
static const int OR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,STRCMP=258
	,STRCPY=259
	,STRCAT=260
	,RETURN=261
	,CONSTRUCT=262
	,CLASS=263
	,IF=264
	,WHILE=265
	,FOR=266
	,ELSE=267
	,START=268
	,END=269
	,START_FUN=270
	,END_FUN=271
	,BGIN_CLASS=272
	,END_CLASS=273
	,SECURE1=274
	,SECURE2=275
	,START_SECURE1=276
	,END_SECURE1=277
	,START_SECURE2=278
	,END_SECURE2=279
	,FLOAT=280
	,INT=281
	,VOID=282
	,ID=283
	,ID_FUNCTIE=284
	,BOOL_VALOARE=285
	,INTEGER_VALOARE=286
	,FLOAT_VALOARE=287
	,BOOL=288
	,STRING=289
	,STRING_VALOARE=290
	,ASSIGN=291
	,NEG=292
	,EGAL=293
	,MAI_MIC=294
	,MIC_EGAL=295
	,MAI_MARE=296
	,MARE_EGAL=297
	,AND=298
	,OR=299


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::STRCMP=258;
const int YY_parse_CLASS::STRCPY=259;
const int YY_parse_CLASS::STRCAT=260;
const int YY_parse_CLASS::RETURN=261;
const int YY_parse_CLASS::CONSTRUCT=262;
const int YY_parse_CLASS::CLASS=263;
const int YY_parse_CLASS::IF=264;
const int YY_parse_CLASS::WHILE=265;
const int YY_parse_CLASS::FOR=266;
const int YY_parse_CLASS::ELSE=267;
const int YY_parse_CLASS::START=268;
const int YY_parse_CLASS::END=269;
const int YY_parse_CLASS::START_FUN=270;
const int YY_parse_CLASS::END_FUN=271;
const int YY_parse_CLASS::BGIN_CLASS=272;
const int YY_parse_CLASS::END_CLASS=273;
const int YY_parse_CLASS::SECURE1=274;
const int YY_parse_CLASS::SECURE2=275;
const int YY_parse_CLASS::START_SECURE1=276;
const int YY_parse_CLASS::END_SECURE1=277;
const int YY_parse_CLASS::START_SECURE2=278;
const int YY_parse_CLASS::END_SECURE2=279;
const int YY_parse_CLASS::FLOAT=280;
const int YY_parse_CLASS::INT=281;
const int YY_parse_CLASS::VOID=282;
const int YY_parse_CLASS::ID=283;
const int YY_parse_CLASS::ID_FUNCTIE=284;
const int YY_parse_CLASS::BOOL_VALOARE=285;
const int YY_parse_CLASS::INTEGER_VALOARE=286;
const int YY_parse_CLASS::FLOAT_VALOARE=287;
const int YY_parse_CLASS::BOOL=288;
const int YY_parse_CLASS::STRING=289;
const int YY_parse_CLASS::STRING_VALOARE=290;
const int YY_parse_CLASS::ASSIGN=291;
const int YY_parse_CLASS::NEG=292;
const int YY_parse_CLASS::EGAL=293;
const int YY_parse_CLASS::MAI_MIC=294;
const int YY_parse_CLASS::MIC_EGAL=295;
const int YY_parse_CLASS::MAI_MARE=296;
const int YY_parse_CLASS::MARE_EGAL=297;
const int YY_parse_CLASS::AND=298;
const int YY_parse_CLASS::OR=299;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		285
#define	YYFLAG		-32768
#define	YYNTBASE	56

#define YYTRANSLATE(x) ((unsigned)(x) <= 299 ? yytranslate[x] : 98)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,    55,     2,     2,     2,     2,    51,
    52,    47,    45,    54,    46,     2,    48,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    53,    49,     2,
     2,     2,     2,    50,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     9,    10,    18,    19,    26,    33,    37,
    38,    48,    51,    55,    62,    68,    69,    77,    79,    83,
    88,    93,   101,   104,   106,   110,   111,   119,   120,   127,
   131,   135,   142,   148,   149,   159,   161,   163,   166,   172,
   178,   184,   188,   191,   194,   201,   208,   215,   216,   221,
   222,   229,   230,   233,   234,   239,   243,   244,   252,   256,
   257,   264,   268,   275,   281,   282,   289,   291,   292,   295,
   300,   305,   307,   309,   311,   323,   331,   339,   350,   352,
   354,   356,   360,   364,   368,   372,   376,   380,   384,   388,
   392,   394,   396,   398,   399,   404,   405,   410,   411,   416,
   417,   422,   423,   428,   430,   432,   434,   436,   438,   440
};

static const short yyrhs[] = {    57,
     0,    56,    57,     0,    94,    28,    49,     0,     0,    94,
    28,    58,    50,    36,    88,    49,     0,     0,    28,    59,
    50,    36,    88,    49,     0,    34,    28,    47,    36,    97,
    49,     0,    34,    28,    49,     0,     0,    94,    29,    60,
    51,    82,    52,    15,    71,    16,     0,    72,    49,     0,
    33,    28,    49,     0,    33,    28,    53,    36,    87,    49,
     0,    28,    53,    36,    87,    49,     0,     0,     8,    28,
    61,    17,    62,    18,    49,     0,    49,     0,    63,    64,
    65,     0,    19,    21,    66,    22,     0,    20,    23,    66,
    24,     0,     7,    51,    82,    52,    15,    71,    16,     0,
    66,    67,     0,    67,     0,    94,    28,    49,     0,     0,
    94,    28,    68,    50,    36,    88,    49,     0,     0,    28,
    69,    50,    36,    88,    49,     0,    34,    28,    49,     0,
    33,    28,    49,     0,    33,    28,    53,    36,    87,    49,
     0,    28,    53,    36,    87,    49,     0,     0,    94,    29,
    70,    51,    82,    52,    15,    71,    16,     0,    78,     0,
    83,     0,    72,    49,     0,     3,    28,    54,    28,    49,
     0,     4,    28,    54,    28,    49,     0,     5,    28,    54,
    28,    49,     0,    71,    72,    49,     0,    71,    78,     0,
    71,    83,     0,    71,     3,    28,    54,    28,    49,     0,
    71,     4,    28,    54,    28,    49,     0,    71,     5,    28,
    54,    28,    49,     0,     0,    29,    73,    51,    52,     0,
     0,    29,    74,    55,    51,    75,    52,     0,     0,    76,
    88,     0,     0,    75,    54,    77,    88,     0,    94,    28,
    49,     0,     0,    94,    28,    79,    50,    36,    88,    49,
     0,    34,    28,    49,     0,     0,    28,    80,    50,    36,
    88,    49,     0,    33,    28,    49,     0,    33,    28,    53,
    36,    87,    49,     0,    28,    53,    36,    87,    49,     0,
     0,     6,    81,    51,    88,    52,    49,     0,    49,     0,
     0,    94,    28,     0,    82,    54,    94,    28,     0,    82,
    54,    33,    28,     0,    84,     0,    85,     0,    86,     0,
     9,    51,    87,    52,    13,    71,    14,    12,    13,    71,
    14,     0,     9,    51,    87,    52,    13,    71,    14,     0,
    10,    51,    87,    52,    13,    71,    14,     0,    11,    51,
    71,    87,    49,    71,    52,    13,    71,    14,     0,    96,
     0,    28,     0,    95,     0,    87,    38,    87,     0,    87,
    37,    87,     0,    87,    41,    87,     0,    87,    39,    87,
     0,    87,    42,    87,     0,    87,    40,    87,     0,    87,
    43,    87,     0,    87,    44,    87,     0,    51,    87,    52,
     0,    95,     0,    28,     0,    72,     0,     0,    88,    45,
    89,    88,     0,     0,    88,    46,    90,    88,     0,     0,
    88,    47,    91,    88,     0,     0,    88,    48,    92,    88,
     0,     0,    51,    93,    88,    52,     0,    26,     0,    25,
     0,    27,     0,    31,     0,    32,     0,    30,     0,    35,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    74,    75,    77,    78,    78,    79,    79,    80,    81,    82,
    82,    83,    84,    85,    86,    87,    87,    88,    91,    94,
    97,   100,   103,   104,   106,   107,   107,   108,   108,   109,
   110,   111,   112,   113,   113,   116,   117,   118,   119,   120,
   121,   122,   123,   124,   125,   126,   127,   130,   130,   131,
   131,   134,   134,   135,   135,   138,   139,   139,   140,   141,
   141,   142,   143,   144,   145,   145,   146,   149,   150,   151,
   152,   155,   156,   157,   160,   161,   164,   167,   170,   171,
   172,   173,   174,   175,   176,   177,   178,   179,   180,   181,
   184,   185,   186,   187,   188,   188,   189,   189,   190,   190,
   191,   191,   191,   194,   195,   196,   199,   200,   203,   205
};

static const char * const yytname[] = {   "$","error","$illegal.","STRCMP","STRCPY",
"STRCAT","RETURN","CONSTRUCT","CLASS","IF","WHILE","FOR","ELSE","START","END",
"START_FUN","END_FUN","BGIN_CLASS","END_CLASS","SECURE1","SECURE2","START_SECURE1",
"END_SECURE1","START_SECURE2","END_SECURE2","FLOAT","INT","VOID","ID","ID_FUNCTIE",
"BOOL_VALOARE","INTEGER_VALOARE","FLOAT_VALOARE","BOOL","STRING","STRING_VALOARE",
"ASSIGN","NEG","EGAL","MAI_MIC","MIC_EGAL","MAI_MARE","MARE_EGAL","AND","OR",
"'+'","'-'","'*'","'/'","';'","'@'","'('","')'","':'","','","'#'","startProgram",
"global","@1","@2","@3","@4","bloc_class","security1","security2","constructor",
"blocsecureR","blocsecure","@5","@6","@7","bloc","apelF","@8","@9","listaParametriiAF",
"@10","@11","local","@12","@13","@14","listaParametriiDF","ifWhileFor","instructiuneIf",
"instructiuneWhile","instructiuneFor","expresieBool","expresieComplexa","@15",
"@16","@17","@18","@19","tipVar","VALOARE_NUMERICA","VALOARE_TIP_BOOL","VALOARE_TIP_STRING",
""
};
#endif

static const short yyr1[] = {     0,
    56,    56,    57,    58,    57,    59,    57,    57,    57,    60,
    57,    57,    57,    57,    57,    61,    57,    57,    62,    63,
    64,    65,    66,    66,    67,    68,    67,    69,    67,    67,
    67,    67,    67,    70,    67,    71,    71,    71,    71,    71,
    71,    71,    71,    71,    71,    71,    71,    73,    72,    74,
    72,    76,    75,    77,    75,    78,    79,    78,    78,    80,
    78,    78,    78,    78,    81,    78,    78,    82,    82,    82,
    82,    83,    83,    83,    84,    84,    85,    86,    87,    87,
    87,    87,    87,    87,    87,    87,    87,    87,    87,    87,
    88,    88,    88,    89,    88,    90,    88,    91,    88,    92,
    88,    93,    88,    94,    94,    94,    95,    95,    96,    97
};

static const short yyr2[] = {     0,
     1,     2,     3,     0,     7,     0,     6,     6,     3,     0,
     9,     2,     3,     6,     5,     0,     7,     1,     3,     4,
     4,     7,     2,     1,     3,     0,     7,     0,     6,     3,
     3,     6,     5,     0,     9,     1,     1,     2,     5,     5,
     5,     3,     2,     2,     6,     6,     6,     0,     4,     0,
     6,     0,     2,     0,     4,     3,     0,     7,     3,     0,
     6,     3,     6,     5,     0,     6,     1,     0,     2,     4,
     4,     1,     1,     1,    11,     7,     7,    10,     1,     1,
     1,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     1,     1,     1,     0,     4,     0,     4,     0,     4,     0,
     4,     0,     4,     1,     1,     1,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
     0,   105,   104,   106,     6,    48,     0,     0,    18,     0,
     1,     0,     0,    16,     0,     0,     0,     0,     0,     0,
     2,    12,     4,    10,     0,     0,     0,     0,     0,    13,
     0,     0,     9,     3,     0,     0,     0,    80,   109,   107,
   108,     0,     0,    81,    79,     0,    49,    52,     0,     0,
     0,    68,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    15,    92,   102,    93,     0,    91,
     0,     0,     0,   110,     0,     0,     0,     0,     0,     0,
     0,     0,    90,    83,    82,    85,    87,    84,    86,    88,
    89,     0,    94,    96,    98,   100,     7,    51,    54,    53,
    14,     8,     0,     0,     0,    69,    28,     0,     0,     0,
    24,     0,    17,     0,     0,    19,     0,     0,     0,     0,
     0,     0,     5,     0,     0,     0,     0,     0,     0,     0,
    20,    23,    26,    34,     0,    68,   103,    95,    97,    99,
   101,    55,     0,     0,     0,    65,     0,     0,     0,    60,
     0,     0,    67,     0,     0,    36,    37,    72,    73,    74,
     0,    71,    70,     0,     0,    31,     0,    30,    25,     0,
     0,    21,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,    11,     0,    43,
    44,    38,    57,     0,     0,     0,     0,    68,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    62,     0,
    59,     0,     0,     0,    42,    56,     0,    33,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,    80,
     0,     0,     0,     0,     0,     0,     0,     0,    29,    32,
     0,     0,     0,    39,    40,    41,     0,     0,     0,     0,
    64,     0,     0,     0,     0,     0,     0,    27,     0,    22,
    66,     0,     0,     0,    61,    63,    45,    46,    47,     0,
     0,    76,    77,     0,    58,    35,     0,     0,     0,     0,
     0,    78,    75,     0,     0
};

static const short yydefgoto[] = {    10,
    11,    35,    16,    36,    25,    54,    55,    82,   116,   110,
   111,   170,   128,   171,   154,    68,    17,    18,    71,    72,
   122,   156,   217,   182,   177,    77,   157,   158,   159,   160,
    43,    69,   118,   119,   120,   121,    92,   161,    44,    45,
    75
};

static const short yypact[] = {    59,
   -17,-32768,-32768,-32768,   -28,   -25,    22,    25,-32768,   191,
-32768,    20,    73,-32768,    70,    16,    74,    66,   -21,   -31,
-32768,-32768,    81,-32768,   116,    -8,   103,   105,   102,-32768,
   135,   136,-32768,-32768,   125,   128,   162,-32768,-32768,-32768,
-32768,    -8,   565,-32768,-32768,    17,-32768,-32768,    -8,   150,
   146,    84,   165,   169,   170,   517,    -8,    -8,    -8,    -8,
    -8,    -8,    -8,    -8,-32768,-32768,-32768,-32768,   147,-32768,
   -10,    17,   578,-32768,   140,    17,    28,   193,   -19,   148,
   203,   215,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    17,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   199,
-32768,-32768,   156,   212,    45,-32768,   175,   206,   207,   101,
-32768,    89,-32768,   -19,   185,-32768,   100,    17,    17,    17,
    17,    17,-32768,   519,   211,   213,   216,   192,     3,   202,
-32768,-32768,   205,-32768,    71,    84,-32768,    95,    95,-32768,
-32768,   199,   227,   229,   230,-32768,   209,   210,   214,   217,
   247,   248,-32768,   295,   228,-32768,-32768,-32768,-32768,-32768,
   259,-32768,-32768,    -8,   266,-32768,   267,-32768,-32768,   257,
   258,-32768,    97,   254,   256,   271,   262,    -8,    -8,   519,
   290,   277,    30,   285,   307,   311,   312,-32768,   292,-32768,
-32768,-32768,   293,   591,    17,    -8,   314,    84,   336,   329,
   330,   331,    17,   533,   549,   263,    -8,   335,-32768,   338,
-32768,   313,   318,   321,-32768,-32768,   316,-32768,   237,   604,
    17,   115,   519,   333,   334,   340,   118,   377,   378,     5,
   617,   630,    17,    -8,   370,   371,   375,   368,-32768,-32768,
   270,   392,   327,-32768,-32768,-32768,   357,   519,   519,   519,
-32768,   300,   643,   360,   361,   362,    17,-32768,   519,-32768,
-32768,   359,   391,   204,-32768,-32768,-32768,-32768,-32768,   332,
   423,   400,-32768,   401,-32768,-32768,   402,   519,   519,   455,
   487,-32768,-32768,   413,-32768
};

static const short yypgoto[] = {-32768,
   411,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   308,
  -106,-32768,-32768,-32768,  -159,     0,-32768,-32768,-32768,-32768,
-32768,  -149,-32768,-32768,-32768,  -133,  -103,-32768,-32768,-32768,
   -23,   -59,-32768,-32768,-32768,-32768,-32768,     2,   -45,-32768,
-32768
};


#define	YYLAST		692


static const short yytable[] = {    12,
    70,    13,   173,   132,   190,     2,     3,     4,   107,    12,
    14,    13,   100,   108,   109,    32,   103,    33,    56,    38,
   206,    39,    40,    41,    15,    73,    70,    30,   132,   -50,
    70,    31,   117,    84,    85,    86,    87,    88,    89,    90,
    91,    98,    42,    99,    66,     6,    70,    40,    41,    19,
   191,   166,    20,    78,   -60,   167,   190,   181,   138,   139,
   140,   141,   142,   243,   222,    27,     1,    67,    22,     2,
     3,     4,    70,    70,    70,    70,    70,   125,   209,   104,
   112,   105,   210,     2,     3,     4,     5,     6,   262,   263,
   264,     7,     8,   190,   172,     2,     3,     4,   107,   271,
    23,    24,   191,   108,   109,    26,   126,     9,     2,     3,
     4,   112,   190,   190,   190,   112,   133,   134,   280,   281,
    29,   190,   131,   155,    28,     2,     3,     4,   107,    34,
   190,   190,    37,   108,   109,   219,   112,    78,    46,   191,
   194,    95,    96,   227,    93,    94,    95,    96,   199,    70,
   105,   137,    48,   189,   204,   205,    47,    70,   191,   191,
   191,   241,    93,    94,    95,    96,   242,   191,   105,   247,
    49,    50,   220,   252,    51,    70,   191,   191,    52,   155,
    53,    76,   231,   232,    74,    79,    80,    70,   102,    81,
   284,    93,    94,    95,    96,    97,   113,   270,     1,    78,
    93,    94,    95,    96,   123,   189,   185,   186,   187,   146,
   253,    70,   147,   148,   149,     2,     3,     4,     5,     6,
   106,   115,   155,     7,     8,   114,   124,   127,     2,     3,
     4,   150,     6,   129,   130,   136,   151,   152,   162,     9,
   163,   165,   189,    93,    94,    95,    96,   155,   155,   155,
   168,   164,   153,   169,   174,   274,   175,   176,   155,   178,
   179,   189,   189,   189,   180,   185,   186,   187,   146,   181,
   189,   147,   148,   149,   183,   184,   192,   155,   155,   189,
   189,    93,    94,    95,    96,   239,   193,     2,     3,     4,
   230,     6,    39,    40,    41,   151,   152,   185,   186,   187,
   146,   195,   196,   147,   148,   149,   197,   200,   198,   201,
   188,   153,   203,    42,    93,    94,    95,    96,   258,     2,
     3,     4,   150,     6,   202,   207,   208,   151,   152,   185,
   186,   187,   146,   211,   212,   147,   148,   149,   213,   214,
   215,   216,   260,   153,    93,    94,    95,    96,   265,   221,
   223,     2,     3,     4,   150,     6,   224,   225,   226,   151,
   152,   185,   186,   187,   146,   238,   235,   147,   148,   149,
   233,   236,   272,   234,   237,   153,    93,    94,    95,    96,
   275,   244,   245,     2,     3,     4,   150,     6,   246,   248,
   249,   151,   152,   185,   186,   187,   146,   254,   255,   147,
   148,   149,   256,   257,   273,   261,   259,   153,   267,   268,
   269,   277,   285,   278,   279,     2,     3,     4,   150,     6,
    21,   135,     0,   151,   152,   185,   186,   187,   146,     0,
     0,   147,   148,   149,     0,     0,     0,     0,   276,   153,
     0,     0,     0,     0,     0,     0,     0,     2,     3,     4,
   150,     6,     0,     0,     0,   151,   152,   185,   186,   187,
   146,     0,     0,   147,   148,   149,     0,     0,   282,     0,
     0,   153,     0,     0,     0,     0,     0,     0,     0,     2,
     3,     4,   150,     6,     0,     0,     0,   151,   152,   185,
   186,   187,   146,     0,     0,   147,   148,   149,     0,     0,
   283,     0,     0,   153,     0,     0,     0,     0,     0,     0,
     0,     2,     3,     4,   150,     6,     0,     0,     0,   151,
   152,   143,   144,   145,   146,     0,     0,   147,   148,   149,
     0,     0,     0,     0,     0,   153,     0,     0,     0,     0,
     0,     0,     0,     2,     3,     4,   150,     6,     0,     0,
     0,   151,   152,    57,    58,    59,    60,    61,    62,    63,
    64,     0,     0,     0,     0,     0,     0,   153,    83,    57,
    58,    59,    60,    61,    62,    63,    64,     0,     0,     0,
     0,     0,     0,     0,   228,    57,    58,    59,    60,    61,
    62,    63,    64,     0,     0,     0,     0,     0,     0,     0,
   229,    57,    58,    59,    60,    61,    62,    63,    64,     0,
     0,     0,     0,    65,    57,    58,    59,    60,    61,    62,
    63,    64,     0,     0,     0,     0,   101,    57,    58,    59,
    60,    61,    62,    63,    64,     0,     0,     0,     0,   218,
    57,    58,    59,    60,    61,    62,    63,    64,     0,     0,
     0,     0,   240,    57,    58,    59,    60,    61,    62,    63,
    64,     0,     0,     0,     0,   250,    57,    58,    59,    60,
    61,    62,    63,    64,     0,     0,     0,     0,   251,    57,
    58,    59,    60,    61,    62,    63,    64,     0,     0,     0,
     0,   266
};

static const short yycheck[] = {     0,
    46,     0,   136,   110,   154,    25,    26,    27,    28,    10,
    28,    10,    72,    33,    34,    47,    76,    49,    42,    28,
   180,    30,    31,    32,    53,    49,    72,    49,   135,    55,
    76,    53,    92,    57,    58,    59,    60,    61,    62,    63,
    64,    52,    51,    54,    28,    29,    92,    31,    32,    28,
   154,    49,    28,    52,    50,    53,   206,    53,   118,   119,
   120,   121,   122,   223,   198,    50,     8,    51,    49,    25,
    26,    27,   118,   119,   120,   121,   122,    33,    49,    52,
    79,    54,    53,    25,    26,    27,    28,    29,   248,   249,
   250,    33,    34,   243,    24,    25,    26,    27,    28,   259,
    28,    29,   206,    33,    34,    36,   105,    49,    25,    26,
    27,   110,   262,   263,   264,   114,    28,    29,   278,   279,
    55,   271,    22,   124,    51,    25,    26,    27,    28,    49,
   280,   281,    17,    33,    34,   195,   135,   136,    36,   243,
   164,    47,    48,   203,    45,    46,    47,    48,    52,   195,
    54,    52,    51,   154,   178,   179,    52,   203,   262,   263,
   264,   221,    45,    46,    47,    48,    52,   271,    54,    52,
    36,    36,   196,   233,    50,   221,   280,   281,    51,   180,
    19,    36,   206,   207,    35,    21,    18,   233,    49,    20,
     0,    45,    46,    47,    48,    49,    49,   257,     8,   198,
    45,    46,    47,    48,    49,   206,     3,     4,     5,     6,
   234,   257,     9,    10,    11,    25,    26,    27,    28,    29,
    28,     7,   223,    33,    34,    23,    15,    53,    25,    26,
    27,    28,    29,    28,    28,    51,    33,    34,    28,    49,
    28,    50,   243,    45,    46,    47,    48,   248,   249,   250,
    49,    36,    49,    49,    28,    52,    28,    28,   259,    51,
    51,   262,   263,   264,    51,     3,     4,     5,     6,    53,
   271,     9,    10,    11,    28,    28,    49,   278,   279,   280,
   281,    45,    46,    47,    48,    49,    28,    25,    26,    27,
    28,    29,    30,    31,    32,    33,    34,     3,     4,     5,
     6,    36,    36,     9,    10,    11,    50,    54,    51,    54,
    16,    49,    51,    51,    45,    46,    47,    48,    49,    25,
    26,    27,    28,    29,    54,    36,    50,    33,    34,     3,
     4,     5,     6,    49,    28,     9,    10,    11,    28,    28,
    49,    49,    16,    49,    45,    46,    47,    48,    49,    36,
    15,    25,    26,    27,    28,    29,    28,    28,    28,    33,
    34,     3,     4,     5,     6,    50,    54,     9,    10,    11,
    36,    54,    14,    36,    54,    49,    45,    46,    47,    48,
    49,    49,    49,    25,    26,    27,    28,    29,    49,    13,
    13,    33,    34,     3,     4,     5,     6,    28,    28,     9,
    10,    11,    28,    36,    14,    49,    15,    49,    49,    49,
    49,    12,     0,    13,    13,    25,    26,    27,    28,    29,
    10,   114,    -1,    33,    34,     3,     4,     5,     6,    -1,
    -1,     9,    10,    11,    -1,    -1,    -1,    -1,    16,    49,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    25,    26,    27,
    28,    29,    -1,    -1,    -1,    33,    34,     3,     4,     5,
     6,    -1,    -1,     9,    10,    11,    -1,    -1,    14,    -1,
    -1,    49,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    25,
    26,    27,    28,    29,    -1,    -1,    -1,    33,    34,     3,
     4,     5,     6,    -1,    -1,     9,    10,    11,    -1,    -1,
    14,    -1,    -1,    49,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    25,    26,    27,    28,    29,    -1,    -1,    -1,    33,
    34,     3,     4,     5,     6,    -1,    -1,     9,    10,    11,
    -1,    -1,    -1,    -1,    -1,    49,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    25,    26,    27,    28,    29,    -1,    -1,
    -1,    33,    34,    37,    38,    39,    40,    41,    42,    43,
    44,    -1,    -1,    -1,    -1,    -1,    -1,    49,    52,    37,
    38,    39,    40,    41,    42,    43,    44,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    52,    37,    38,    39,    40,    41,
    42,    43,    44,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    52,    37,    38,    39,    40,    41,    42,    43,    44,    -1,
    -1,    -1,    -1,    49,    37,    38,    39,    40,    41,    42,
    43,    44,    -1,    -1,    -1,    -1,    49,    37,    38,    39,
    40,    41,    42,    43,    44,    -1,    -1,    -1,    -1,    49,
    37,    38,    39,    40,    41,    42,    43,    44,    -1,    -1,
    -1,    -1,    49,    37,    38,    39,    40,    41,    42,    43,
    44,    -1,    -1,    -1,    -1,    49,    37,    38,    39,    40,
    41,    42,    43,    44,    -1,    -1,    -1,    -1,    49,    37,
    38,    39,    40,    41,    42,    43,    44,    -1,    -1,    -1,
    -1,    49
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 3:
#line 77 "tema.y"
{ declarareVariabila(yyvsp[-2].tip,yyvsp[-1].id, "", 0);;
    break;}
case 4:
#line 78 "tema.y"
{ declarareVariabila(yyvsp[-1].tip,yyvsp[0].id, "", 0); startAssignExpr(yyvsp[0].id);;
    break;}
case 5:
#line 78 "tema.y"
{ endAssign(yyvsp[-5].id); ;
    break;}
case 6:
#line 79 "tema.y"
{ startAssignExpr(yyvsp[0].id);;
    break;}
case 7:
#line 79 "tema.y"
{ endAssign(yyvsp[-5].id); ;
    break;}
case 8:
#line 80 "tema.y"
{ declarareVariabila(yyvsp[-5].uTipString,yyvsp[-4].id, yyvsp[-1].stringValue, 0); ;
    break;}
case 10:
#line 82 "tema.y"
{ declarareFunctie(yyvsp[-1].tip,yyvsp[0].id); pushScope(yyvsp[0].id); ;
    break;}
case 13:
#line 84 "tema.y"
{ declarareVariabila(yyvsp[-2].uTipBool,yyvsp[-1].id, "", 0); ;
    break;}
case 14:
#line 85 "tema.y"
{ declarareVariabila(yyvsp[-5].uTipBool,yyvsp[-4].id, yyvsp[-1].exprBool, 0); ;
    break;}
case 16:
#line 87 "tema.y"
{ pushScope(yyvsp[0].id); declarareClasa(yyvsp[0].id); ;
    break;}
case 25:
#line 106 "tema.y"
{ declarareVariabila(yyvsp[-2].tip,yyvsp[-1].id, "", 0);;
    break;}
case 26:
#line 107 "tema.y"
{ declarareVariabila(yyvsp[-1].tip,yyvsp[0].id, "", 0); startAssignExpr(yyvsp[0].id);;
    break;}
case 27:
#line 107 "tema.y"
{ endAssign(yyvsp[-5].id); ;
    break;}
case 28:
#line 108 "tema.y"
{ startAssignExpr(yyvsp[0].id);;
    break;}
case 29:
#line 108 "tema.y"
{ endAssign(yyvsp[-5].id); ;
    break;}
case 31:
#line 110 "tema.y"
{ declarareVariabila(yyvsp[-2].uTipBool,yyvsp[-1].id, "", 0); ;
    break;}
case 32:
#line 111 "tema.y"
{ declarareVariabila(yyvsp[-5].uTipBool,yyvsp[-4].id, yyvsp[-1].exprBool, 0); ;
    break;}
case 34:
#line 113 "tema.y"
{ declarareFunctie(yyvsp[-1].tip,yyvsp[0].id); pushScope(yyvsp[0].id); ;
    break;}
case 48:
#line 130 "tema.y"
{ apelFunctie(yyvsp[0].id); ;
    break;}
case 49:
#line 130 "tema.y"
{ endApelFunctie(yyvsp[-3].id); ;
    break;}
case 50:
#line 131 "tema.y"
{ apelFunctie(yyvsp[0].id); ;
    break;}
case 51:
#line 131 "tema.y"
{ endApelFunctie(yyvsp[-5].id); ;
    break;}
case 52:
#line 134 "tema.y"
{ pushStackParan(); ;
    break;}
case 53:
#line 134 "tema.y"
{ popStackParan("fun_call"); ;
    break;}
case 54:
#line 135 "tema.y"
{ pushStackParan(); ;
    break;}
case 55:
#line 135 "tema.y"
{ popStackParan("fun_call"); ;
    break;}
case 56:
#line 138 "tema.y"
{ declarareVariabila(yyvsp[-2].tip,yyvsp[-1].id, "", 0);;
    break;}
case 57:
#line 139 "tema.y"
{ declarareVariabila(yyvsp[-1].tip,yyvsp[0].id, "", 0); startAssignExpr(yyvsp[0].id);;
    break;}
case 58:
#line 139 "tema.y"
{ endAssign(yyvsp[-5].id); ;
    break;}
case 60:
#line 141 "tema.y"
{ startAssignExpr(yyvsp[0].id);;
    break;}
case 61:
#line 141 "tema.y"
{ endAssign(yyvsp[-5].id); ;
    break;}
case 62:
#line 142 "tema.y"
{ declarareVariabila(yyvsp[-2].uTipBool,yyvsp[-1].id, "", 0); ;
    break;}
case 63:
#line 143 "tema.y"
{ declarareVariabila(yyvsp[-5].uTipBool,yyvsp[-4].id, yyvsp[-1].exprBool, 0); ;
    break;}
case 65:
#line 145 "tema.y"
{ startAssignExpr("return");;
    break;}
case 66:
#line 145 "tema.y"
{ endAssign("return"); ;
    break;}
case 69:
#line 150 "tema.y"
{ declarareVariabila(yyvsp[-1].tip,yyvsp[0].id, "", 1);;
    break;}
case 70:
#line 151 "tema.y"
{ declarareVariabila(yyvsp[-1].tip,yyvsp[0].id, "", 1);;
    break;}
case 71:
#line 152 "tema.y"
{ declarareVariabila(yyvsp[-1].uTipBool,yyvsp[0].id, "", 1);;
    break;}
case 79:
#line 170 "tema.y"
{ yyval.exprBool = yyval.boolValoare ;;
    break;}
case 80:
#line 171 "tema.y"
{ evaluareIdCaBool(yyval.exprBool, yyvsp[0].id); ;
    break;}
case 81:
#line 172 "tema.y"
{ yyval.exprBool = yyvsp[0].exprNumeric; ;
    break;}
case 82:
#line 173 "tema.y"
{ evalExpresieBool(yyval.exprBool, yyvsp[-2].exprBool, "==",yyvsp[0].exprBool); ;
    break;}
case 83:
#line 174 "tema.y"
{ evalExpresieBool(yyval.exprBool, yyvsp[-2].exprBool, "!=",yyvsp[0].exprBool); ;
    break;}
case 84:
#line 175 "tema.y"
{ evalExpresieBool(yyval.exprBool, yyvsp[-2].exprBool, ">=",yyvsp[0].exprBool); ;
    break;}
case 85:
#line 176 "tema.y"
{ evalExpresieBool(yyval.exprBool, yyvsp[-2].exprBool, "<",yyvsp[0].exprBool); ;
    break;}
case 86:
#line 177 "tema.y"
{ evalExpresieBool(yyval.exprBool, yyvsp[-2].exprBool, ">=",yyvsp[0].exprBool); ;
    break;}
case 87:
#line 178 "tema.y"
{ evalExpresieBool(yyval.exprBool, yyvsp[-2].exprBool, "<=",yyvsp[0].exprBool); ;
    break;}
case 88:
#line 179 "tema.y"
{ evalExpresieBool(yyval.exprBool, yyvsp[-2].exprBool, "and",yyvsp[0].exprBool); ;
    break;}
case 89:
#line 180 "tema.y"
{ evalExpresieBool(yyval.exprBool, yyvsp[-2].exprBool, "or",yyvsp[0].exprBool); ;
    break;}
case 90:
#line 181 "tema.y"
{ yyval.exprBool = yyvsp[-1].exprBool; ;
    break;}
case 91:
#line 184 "tema.y"
{ pushExpresieValuePeStack(yyvsp[0].exprNumeric); ;
    break;}
case 92:
#line 185 "tema.y"
{ pushExpresieIdPeStack(yyvsp[0].id); ;
    break;}
case 94:
#line 187 "tema.y"
{ pushOperatorStack("+"); ;
    break;}
case 96:
#line 188 "tema.y"
{ pushOperatorStack("-"); ;
    break;}
case 98:
#line 189 "tema.y"
{ pushOperatorStack("*"); ;
    break;}
case 100:
#line 190 "tema.y"
{ pushOperatorStack("/"); ;
    break;}
case 102:
#line 191 "tema.y"
{ pushStackParan(); ;
    break;}
case 103:
#line 191 "tema.y"
{ popStackParan(""); ;
    break;}
case 107:
#line 199 "tema.y"
{ yyval.exprNumeric = yyval.numericValoare ; ;
    break;}
case 108:
#line 200 "tema.y"
{ yyval.exprNumeric = yyval.numericValoare ; ;
    break;}
case 109:
#line 203 "tema.y"
{ yyval.boolValoare = yyval.boolValoare;;
    break;}
case 110:
#line 205 "tema.y"
{ yyval.stringValue = yyval.stringValue;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 208 "tema.y"

void yyerror(char * s) {
  scriereInTabelDeSimboluri();
  printf("eroare: %s la linia:%d\n",s,yylineno);
}
int main(int argc, char** argv) {
  yyin = fopen(argv[1],"r");
  yyparse();
  scriereInTabelDeSimboluri();
} 